{% set name = "copulas" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/copulas-{{ version }}.tar.gz
  sha256: c518c10bdee7eb63893f8d814e5c2a16125ed13ea44ad68559e3e12160d21166

build:
  number: 0
  skip: True # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - wheel
    - python
    - setuptools
    - pytest-runner 6.0.0
  run:
    - python
    - matplotlib-base >=3.4.0,<4
    - numpy >=1.20.0,<2
    - pandas >=1.1.3
    - scipy >=1.5.4,<2

test:
  imports:
    - copulas
    - copulas.bivariate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdv-dev/Copulas
  summary: Create tabular synthetic data using copulas-based modeling.
  description: |
    Copulas is a Python library for modeling multivariate distributions and
    sampling from them using copula functions. Given a table of numerical
    data, use Copulas to learn the distribution and generate new synthetic
    data following the same statistical properties.
  license: BUSL-1.1
  license_file: LICENSE
  license_family: Other
  doc_url: https://sdv.dev/Copulas/

extra:
  recipe-maintainers:
    - conda-forge/sdv
